window.matchMedia=window.matchMedia||function(a,b){var d,f=a.documentElement,n=f.firstElementChild||f.firstChild,h=a.createElement("body"),c=a.createElement("div");c.id="mq-test-1";c.style.cssText="position:absolute;top:-100em";h.style.background="none";h.appendChild(c);return function(a){c.innerHTML='&shy;<style media="'+a+'"> #mq-test-1 { width: 42px; }</style>';f.insertBefore(h,n);d=42==c.offsetWidth;f.removeChild(h);return{matches:d,media:a}}}(document);
(function(a){function b(){u(!0)}a.respond={};respond.update=function(){};respond.mediaQueriesSupported=a.matchMedia&&a.matchMedia("only all").matches;if(!respond.mediaQueriesSupported){var d=a.document,f=d.documentElement,n=[],h=[],c=[],g={},p=d.getElementsByTagName("head")[0]||f,B=d.getElementsByTagName("base")[0],q=p.getElementsByTagName("link"),k=[],y=function(){for(var C=q.length,b=0,e,c,f,d;b<C;b++)e=q[b],c=e.href,f=e.media,d=e.rel&&"stylesheet"===e.rel.toLowerCase(),c&&d&&!g[c]&&(e.styleSheet&&
e.styleSheet.rawCssText?(t(e.styleSheet.rawCssText,c,f),g[c]=!0):(/^([a-zA-Z:]*\/\/)/.test(c)||B)&&c.replace(RegExp.$1,"").split("/")[0]!==a.location.host||k.push({href:c,media:f}));x()},x=function(){if(k.length){var a=k.shift();D(a.href,function(b){t(b,a.href,a.media);g[a.href]=!0;x()})}},t=function(a,b,e){var c=a.match(/@media[^\{]+\{([^\{\}]*\{[^\}\{]*\})+/gi),f=c&&c.length||0;b=b.substring(0,b.lastIndexOf("/"));var d=function(a){return a.replace(/(url\()['"]?([^\/\)'"][^:\)'"]+)['"]?(\))/g,"$1"+
b+"$2$3")},m=!f&&e,p=0,g,s,q,k;b.length&&(b+="/");for(m&&(f=1);p<f;p++)for(g=0,m?(s=e,h.push(d(a))):(s=c[p].match(/@media *([^\{]+)\{([\S\s]+?)$/)&&RegExp.$1,h.push(RegExp.$2&&d(RegExp.$2))),q=s.split(","),k=q.length;g<k;g++)s=q[g],n.push({media:s.split("(")[0].match(/(only\s+)?([a-zA-Z]+)\s?/)&&RegExp.$2||"all",rules:h.length-1,hasquery:-1<s.indexOf("("),minw:s.match(/\(min\-width:[\s]*([\s]*[0-9\.]+)(px|em)[\s]*\)/)&&parseFloat(RegExp.$1)+(RegExp.$2||""),maxw:s.match(/\(max\-width:[\s]*([\s]*[0-9\.]+)(px|em)[\s]*\)/)&&
parseFloat(RegExp.$1)+(RegExp.$2||"")});u()},v,z,A=function(){var a,b=d.createElement("div"),e=d.body,c=!1;b.style.cssText="position:absolute;font-size:1em;width:1em";e||(e=c=d.createElement("body"),e.style.background="none");e.appendChild(b);f.insertBefore(e,f.firstChild);a=b.offsetWidth;c?f.removeChild(e):e.removeChild(b);return a=w=parseFloat(a)},w,u=function(a){var b=f.clientWidth,e="CSS1Compat"===d.compatMode&&b||d.body.clientWidth||b,b={},g=q[q.length-1],l=(new Date).getTime();if(a&&v&&30>l-
v)clearTimeout(z),z=setTimeout(u,30);else{v=l;for(var r in n){a=n[r];var l=a.minw,m=a.maxw,k=null===l,t=null===m;l&&(l=parseFloat(l)*(-1<l.indexOf("em")?w||A():1));m&&(m=parseFloat(m)*(-1<m.indexOf("em")?w||A():1));a.hasquery&&(k&&t||!(k||e>=l)||!(t||e<=m))||(b[a.media]||(b[a.media]=[]),b[a.media].push(h[a.rules]))}for(r in c)c[r]&&c[r].parentNode===p&&p.removeChild(c[r]);for(r in b)e=d.createElement("style"),a=b[r].join("\n"),e.type="text/css",e.media=r,p.insertBefore(e,g.nextSibling),e.styleSheet?
e.styleSheet.cssText=a:e.appendChild(d.createTextNode(a)),c.push(e)}},D=function(a,b){var c=E();c&&(c.open("GET",a,!0),c.onreadystatechange=function(){4!=c.readyState||200!=c.status&&304!=c.status||b(c.responseText)},4!=c.readyState&&c.send(null))},E=function(){var a=!1;try{a=new XMLHttpRequest}catch(b){a=new ActiveXObject("Microsoft.XMLHTTP")}return function(){return a}}();y();respond.update=y;a.addEventListener?a.addEventListener("resize",b,!1):a.attachEvent&&a.attachEvent("onresize",b)}})(this);
jQuery(document).ready(function(a){a("a[href=#scroll-top]").click(function(){a("html, body").animate({scrollTop:0},"slow");return!1})});
(function(a){a.simplePlaceholder={placeholderClass:null,hidePlaceholder:function(){var b=a(this);b.val()==b.attr("placeholder")&&b.data(a.simplePlaceholder.placeholderData)&&b.val("").removeClass(a.simplePlaceholder.placeholderClass).data(a.simplePlaceholder.placeholderData,!1)},showPlaceholder:function(){var b=a(this);""==b.val()&&b.val(b.attr("placeholder")).addClass(a.simplePlaceholder.placeholderClass).data(a.simplePlaceholder.placeholderData,!0)},preventPlaceholderSubmit:function(){a(this).find(".simple-placeholder").each(function(b){b=
a(this);b.val()==b.attr("placeholder")&&b.data(a.simplePlaceholder.placeholderData)&&b.val("")});return!0}};a.fn.simplePlaceholder=function(b){if(void 0==document.createElement("input").placeholder){var d={placeholderClass:"placeholding",placeholderData:"simplePlaceholder.placeholding"};b&&a.extend(d,b);a.extend(a.simplePlaceholder,d);this.each(function(){var b=a(this);b.focus(a.simplePlaceholder.hidePlaceholder);b.blur(a.simplePlaceholder.showPlaceholder);b.data(a.simplePlaceholder.placeholderData,
!1);""==b.val()&&(b.val(b.attr("placeholder")),b.addClass(a.simplePlaceholder.placeholderClass),b.data(a.simplePlaceholder.placeholderData,!0));b.addClass("simple-placeholder");a(this.form).submit(a.simplePlaceholder.preventPlaceholderSubmit)})}return this}})(jQuery);
(function(a){a.fn.fitVids=function(b){var d={customSelector:null},f=document.createElement("div"),n=document.getElementsByTagName("base")[0]||document.getElementsByTagName("script")[0];f.className="fit-vids-style";f.innerHTML="&shy;<style>         .fluid-width-video-wrapper {        width: 100%;                     position: relative;              padding: 0;                      }                                   .fluid-width-video-wrapper iframe,  .fluid-width-video-wrapper object,  .fluid-width-video-wrapper embed {  position: absolute;              top: 0;                          left: 0;                         width: 100%;                     height: 100%;                    }                                   </style>";n.parentNode.insertBefore(f,
n);b&&a.extend(d,b);return this.each(function(){var b=["iframe[src*='player.vimeo.com']","iframe[src*='www.youtube.com']","iframe[src*='www.youtube-nocookie.com']","iframe[src*='fast.wistia.com']","embed"];d.customSelector&&b.push(d.customSelector);a(this).find(b.join(",")).each(function(){var b=a(this);if(!("embed"===this.tagName.toLowerCase()&&b.parent("object").length||b.parent(".fluid-width-video-wrapper").length)){var d="object"===this.tagName.toLowerCase()||b.attr("height")&&!isNaN(parseInt(b.attr("height"),
10))?parseInt(b.attr("height"),10):b.height(),f=isNaN(parseInt(b.attr("width"),10))?b.width():parseInt(b.attr("width"),10),d=d/f;b.attr("id")||(f="fitvid"+Math.floor(999999*Math.random()),b.attr("id",f));b.wrap('<div class="fluid-width-video-wrapper"></div>').parent(".fluid-width-video-wrapper").css("padding-top",100*d+"%");b.removeAttr("height").removeAttr("width")}})})}})(jQuery);
(function(a){var b=a(".main-nav li.current-menu-item a").html(),b=a(".main-nav li.current_page_item a").html();if(a("span").hasClass("custom-mobile-menu-title"))b=a("span.custom-mobile-menu-title").html();else if("undefined"==typeof b||null===b)b=a("body").hasClass("home")?a("#logo span").hasClass("site-name")?a("#logo .site-name a").html():a("#logo img").attr("alt"):a("body").hasClass("woocommerce")&&a("h1").hasClass("page-title")?a("h1.page-title").html():a("body").hasClass("woocommerce")&&a("h1").hasClass("entry-title")?
a("h1.entry-title").html():a("body").hasClass("archive")&&a("h6").hasClass("title-archive")?a("h6.title-archive").html():a("body").hasClass("search-results")&&a("h6").hasClass("title-search-results")?a("h6.title-search-results").html():a("body").hasClass("page-template-blog-excerpt-php")&&a("li").hasClass("current_page_item")?a("li.current_page_item").text():a("body").hasClass("page-template-blog-php")&&a("li").hasClass("current_page_item")?a("li.current_page_item").text():a("h1").hasClass("post-title")?
a("h1.post-title").html():"&nbsp;";a(".main-nav").append('<a id="responsive_menu_button"></a>');a(".main-nav").prepend('<div id="responsive_current_menu_item">'+b+"</div>");a("a#responsive_menu_button, #responsive_current_menu_item").click(function(){a(".js .main-nav .menu").slideToggle(function(){a(this).is(":visible")?a("a#responsive_menu_button").addClass("responsive-toggle-open"):(a("a#responsive_menu_button").removeClass("responsive-toggle-open"),a(".js .main-nav .menu").removeAttr("style"))})})})(jQuery);
(function(a){a("html").click(function(){a("a#responsive_menu_button").hasClass("responsive-toggle-open")&&a(".js .main-nav .menu").slideToggle(function(){a("a#responsive_menu_button").removeClass("responsive-toggle-open");a(".js .main-nav .menu").removeAttr("style")})})})(jQuery);jQuery(".main-nav").click(function(a){"/wp-admin/customize.php"!=window.location.pathname&&a.stopPropagation()});jQuery(function(){jQuery("input[placeholder], textarea[placeholder]").simplePlaceholder()});jQuery(document).ready(function(){jQuery("#wrapper").fitVids()});